---
- from:
    entity: account
  to:
    entity: account_role
  relationship_type: has_many
  associate_delete: true
  require: true
- from:
    entity: role
  to:
    entity: account_role
  relationship_type: has_many
  associate_delete: true
  require: true
- from:
    entity: role
  to:
    entity: role_ability
  relationship_type: has_many
  associate_delete: true
  require: true
- from:
    entity: ability
  to:
    entity: role_ability
  relationship_type: has_many
  associate_delete: true
  require: true
- from:
    entity: ability_group
  to:
    entity: ability
  relationship_type: has_many
  associate_delete: true
  require: true
...
